platform :ios, "10.0"
use_frameworks!

target "demo" do
project  "demo.xcodeproj"

#pod 'Kingfisher', '~> 6.3.0'
pod 'SnapKit', '~> 5.0.1'
#
#pod 'RxSwift', '~> 5.0.0'
#pod 'RxCocoa', '~> 5.0.0'
#
#pod 'ObjectMapper', '~> 3.5.1'
end
